function show_analysis_buttons(handles)
    set_visibility(                    ...
        [
            handles.b_show_signal_onsets,   ...
            handles.b_show_df_onsets,       ...
            handles.b_showplot,             ...
            handles.b_showdf,               ...
            handles.b_clear,                ...
            handles.t_playbackspeed,        ...
            handles.b_clear_threshold,      ...
            handles.t_threshold,            ...
        ], 'On');
end