function show_player_buttons(handles)
    set_visibility(...
       [
        handles.s_playbackspeed,...
        handles.b_play,         ...
        handles.b_pause,        ...
        handles.b_stop,         ...
        handles.b_reset_playback_speed
       ],'On');
end